const dpEnum = Object.freeze({
    ETH_CHAIN_TRACK_SERVICE_ENABLED: "ETH_CHAIN_TRACK_SERVICE_ENABLED",
    ETH_POSITION_UPDATOR_SERVICE_ENABLED: "ETH_POSITION_UPDATOR_SERVICE_ENABLED",
    ALERTING_SERVICE_SLEEPTIME: "ALERTING_SERVICE_SLEEPTIME",
    DISCORD_ALERT_PROCESSING_BATCH_LIMIT: "DISCORD_ALERT_PROCESSING_BATCH_LIMIT"
})

module.exports = dpEnum;