const dpEnum = Object.freeze({
    ETH_CHAIN_TRACK_SERVICE_ENABLED: "ETH_CHAIN_TRACK_SERVICE_ENABLED",
    ETH_POSITION_UPDATOR_SERVICE_ENABLED: "ETH_POSITION_UPDATOR_SERVICE_ENABLED",
    ALERT_PROCESSING_BATCH_LIMIT: "ALERT_PROCESSING_BATCH_LIMIT",
    ALERTING_SERVICE_SLEEPTIME: "ALERTING_SERVICE_SLEEPTIME"
})

module.exports = dpEnum;