const dpEnum = Object.freeze({
    ETH_CHAIN_TRACK_SERVICE_ENABLED: "ETH_CHAIN_TRACK_SERVICE_ENABLED",
    ETH_POSITION_UPDATOR_SERVICE_ENABLED: "ETH_POSITION_UPDATOR_SERVICE_ENABLED",
    DISCORD_ALERTING_SERVICE_SLEEPTIME: "DISCORD_ALERTING_SERVICE_SLEEPTIME",
    EMAIL_ALERTING_SERVICE_SLEEPTIME: "EMAIL_ALERTING_SERVICE_SLEEPTIME",
    DISCORD_ALERT_PROCESSING_BATCH_LIMIT: "DISCORD_ALERT_PROCESSING_BATCH_LIMIT",
    EMAIL_ALERT_PROCESSING_BATCH_LIMIT: "EMAIL_ALERT_PROCESSING_BATCH_LIMIT",
    PUSH_ALERT_PROCESSING_BATCH_LIMIT: "PUSH_ALERT_PROCESSING_BATCH_LIMIT",
    PUSH_ALERTING_SERVICE_SLEEPTIME: "PUSH_ALERTING_SERVICE_SLEEPTIME",
    SLACK_ALERT_PROCESSING_BATCH_LIMIT: "SLACK_ALERT_PROCESSING_BATCH_LIMIT",
    SLACK_ALERTING_SERVICE_SLEEPTIME: "SLACK_ALERTING_SERVICE_SLEEPTIME",
    AAVE_V2_HEALTH_FACTOR_THRESHOLD: "AAVE_V2_HEALTH_FACTOR_THRESHOLD",
    CMT_ORDER_PROCESSING_LIMIT: "CMT_ORDER_PROCESSING_LIMIT",
    CMT_ORDER_PROCESSING_SLEEP_TIME:"CMT_ORDER_PROCESSING_SLEEP_TIME"
})

module.exports = dpEnum;